import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Link2, Loader2, Plus, RefreshCw, Star, UserCheck, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { useI18n } from "@/lib/i18n";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useCities } from "@/hooks/useListings";
import { uploadImages } from "@/lib/dashboardForms";
import { PROVIDER_INTENTS } from "@/lib/providerIntents";
import { isPlausibleWhatsapp } from "@/lib/whatsapp";
import { absoluteUrl } from "@/lib/siteUrl";
import PhotoPicker from "@/components/dashboard/PhotoPicker";
import { Button } from "@/components/ui/button";

/**
 * ASSISTED ONBOARDING.
 *
 * The Operations Officer sits with a provider in person and fills this in on
 * their behalf. The row is created with NO `user_id` — an unclaimed profile,
 * exactly like the editorial/unclaimed rows the app already handles: messaging
 * and booking surfaces render the existing "hasn't joined yet" state because
 * `resolveUserIdForMessaging` finds no auth user behind the record.
 *
 * The provider later opens a claim link. The token is generated by
 * `admin_create_provider_claim` (SECURITY DEFINER, admin-only) and only its
 * SHA-256 hash is stored, so nothing in the database can reconstruct a working
 * link. `claim_provider_profile` binds the profile to the signed-in account and
 * refuses a used, revoked, expired or already-owned profile.
 */

type Row = {
  id: string;
  name_en: string;
  name_ar: string | null;
  role: string;
  slug: string | null;
  status: string | null;
  user_id: string | null;
  city_en: string | null;
  created_at: string;
};

type TokenRow = {
  id: string;
  provider_id: string;
  expires_at: string;
  claimed_at: string | null;
  revoked_at: string | null;
};

const slugify = (input: string) =>
  input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 48) || "provider";

/**
 * Role options the admin can pick from. These are the seven public
 * plain-language statements PLUS `whos-who`, which is invitation-only: it is
 * absent from public onboarding on purpose and can only be created here.
 */
const ADMIN_ROLE_OPTIONS: { key: string; role: string; statement: { en: string; ar: string } }[] = [
  ...PROVIDER_INTENTS.map((i) => ({ key: i.key as string, role: i.role as string, statement: i.statement })),
  {
    key: "whos-who-invite",
    role: "whos-who",
    statement: {
      en: "Who's Who — someone Sandal is recognising (invitation only)",
      ar: "من يكون من — شخصية تكرّمها سندال (بدعوة فقط)",
    },
  },
];

type OwnerlessEntry = { id: string; name_en: string; name_ar: string | null; city_id: string | null };

const AdminAssistedProviders = () => {
  const { lang } = useI18n();
  const ar = lang === "ar";
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const { data: cities = [] } = useCities();

  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [intentKey, setIntentKey] = useState(ADMIN_ROLE_OPTIONS[0].key);
  const [nameAr, setNameAr] = useState("");
  const [nameEn, setNameEn] = useState("");
  const [bio, setBio] = useState("");
  const [cityId, setCityId] = useState("");
  const [whatsapp, setWhatsapp] = useState("");
  const [specialties, setSpecialties] = useState("");
  const [photo, setPhoto] = useState<File[]>([]);
  const [links, setLinks] = useState<Record<string, string>>({});
  const [adoptOpen, setAdoptOpen] = useState(false);
  const [adoptSearch, setAdoptSearch] = useState("");
  const [adopting, setAdopting] = useState<string | null>(null);


  const { data: rows = [], isLoading } = useQuery({
    queryKey: ["admin-assisted-providers"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("providers")
        .select("id, name_en, name_ar, role, slug, status, user_id, city_en, created_at")
        .order("created_at", { ascending: false })
        .limit(200);
      if (error) throw error;
      return (data ?? []) as unknown as Row[];
    },
  });

  const { data: tokens = [] } = useQuery({
    queryKey: ["admin-claim-tokens"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("provider_claim_tokens")
        .select("id, provider_id, expires_at, claimed_at, revoked_at")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as unknown as TokenRow[];
    },
  });

  // Seeded Who's Who directory entries with no owner. Sandal already lists
  // these people; adopting one creates the matching provider row and issues a
  // claim link so the real person can take ownership.
  const { data: ownerless = [] } = useQuery({
    queryKey: ["admin-ownerless-whos-who"],
    enabled: adoptOpen,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("whos_who")
        .select("id, name_en, name_ar, city_id")
        .is("user_id", null)
        .order("name_en")
        .limit(500);
      if (error) throw error;
      return (data ?? []) as unknown as OwnerlessEntry[];
    },
  });

  const adoptResults = useMemo(() => {
    const q = adoptSearch.trim().toLowerCase();
    const list = q
      ? ownerless.filter(
          (e) => e.name_en.toLowerCase().includes(q) || (e.name_ar || "").includes(adoptSearch.trim()),
        )
      : ownerless;
    return list.slice(0, 20);
  }, [ownerless, adoptSearch]);

  // Only profiles that were created without an owner are relevant here, plus the
  // ones that have since been claimed through a link.
  const managed = useMemo(() => {
    const withToken = new Set(tokens.map((t) => t.provider_id));
    return rows.filter((r) => !r.user_id || withToken.has(r.id));
  }, [rows, tokens]);

  const tokenFor = (providerId: string) =>
    tokens.find((t) => t.provider_id === providerId && !t.revoked_at) ?? null;

  const resetForm = () => {
    setNameAr("");
    setNameEn("");
    setBio("");
    setCityId("");
    setWhatsapp("");
    setSpecialties("");
    setPhoto([]);
  };

  const adopt = async (entry: OwnerlessEntry) => {
    setAdopting(entry.id);
    const { data, error } = await supabase.rpc("admin_adopt_whos_who", { _whos_who_id: entry.id });
    setAdopting(null);
    if (error || !data) {
      toast.error(error?.message || (ar ? "تعذّر إنشاء الرابط" : "Could not create the link"));
      return;
    }
    const result = data as unknown as { provider_id: string; token: string };
    const url = absoluteUrl(`/claim/${result.token}`);
    setLinks((prev) => ({ ...prev, [result.provider_id]: url }));
    await queryClient.invalidateQueries({ queryKey: ["admin-assisted-providers"] });
    await queryClient.invalidateQueries({ queryKey: ["admin-claim-tokens"] });
    try {
      await navigator.clipboard.writeText(url);
      toast.success(ar ? "تم نسخ رابط الاستحواذ" : "Claim link copied");
    } catch {
      toast.success(ar ? "تم إنشاء الرابط" : "Link created");
    }
  };

  const create = async () => {
    const intent = ADMIN_ROLE_OPTIONS.find((i) => i.key === intentKey)!;
    const displayEn = nameEn.trim() || nameAr.trim();

    if (!displayEn) {
      toast.error(ar ? "الاسم مطلوب" : "A name is required");
      return;
    }
    if (whatsapp.trim() && !isPlausibleWhatsapp(whatsapp)) {
      toast.error(ar ? "رقم الواتساب غير صحيح" : "That WhatsApp number is not valid");
      return;
    }
    setSaving(true);

    let avatar: string | null = null;
    if (photo.length > 0 && user) {
      try {
        const [url] = await uploadImages(photo, user.id, "profile-photos");
        avatar = url ?? null;
      } catch {
        toast.error(ar ? "تعذّر تحميل الصورة" : "Could not upload the photo");
      }
    }

    const city = cities.find((c) => c.id === cityId);
    const specialtyList = specialties
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    const { data: inserted, error } = await supabase
      .from("providers")
      .insert({
        user_id: null,
        role: intent.role,
        name_en: displayEn,
        name_ar: nameAr.trim() || null,
        slug: `${slugify(displayEn)}-${Math.random().toString(36).slice(2, 8)}`,
        bio_en: bio.trim() || null,
        avatar,
        whatsapp: whatsapp.trim() || null,
        city_en: city?.name_en ?? null,
        city_ar: city?.name_ar ?? null,
        specialties: specialtyList.length ? specialtyList : null,
        status: bio.trim() || avatar ? "published" : "draft",
      } as never)
      .select("id, name_en")
      .maybeSingle();

    if (error || !inserted) {
      setSaving(false);
      toast.error(error?.message || (ar ? "تعذّر الإنشاء" : "Could not create the profile"));
      return;
    }

    // Satellite directory row, owner-less like the provider row itself.
    const satellitePayloads: Record<string, { table: string; payload: Record<string, unknown> }> = {
      organization: {
        table: "organizations",
        payload: {
          owner_id: null,
          name_en: displayEn,
          name_ar: nameAr.trim() || null,
          slug: `org-${slugify(displayEn)}`,
          description_en: bio.trim() || null,
          logo: avatar,
          city_id: city?.id ?? null,
          region_id: city?.region_id ?? null,
          status: "published",
        },
      },
      "whos-who": {
        table: "whos_who",
        payload: {
          user_id: null,
          name_en: displayEn,
          name_ar: nameAr.trim() || null,
          slug: `ww-${slugify(displayEn)}`,
          bio_en: bio.trim() || null,
          image: avatar,
          city_id: city?.id ?? null,
          region_id: city?.region_id ?? null,
          status: "published",
        },
      },
      "culture-actor": {
        table: "culture_actors",
        payload: {
          user_id: null,
          name_en: displayEn,
          name_ar: nameAr.trim() || null,
          slug: `ca-${slugify(displayEn)}`,
          bio_en: bio.trim() || null,
          image: avatar,
          region_id: city?.region_id ?? null,
          status: "published",
        },
      },
    };

    const sat = satellitePayloads[intent.role];
    let satelliteId: string | null = null;
    if (sat) {
      const { data: satRow, error: satError } = await (supabase.from(sat.table as never) as never as {
        insert: (v: Record<string, unknown>) => {
          select: (c: string) => {
            maybeSingle: () => Promise<{ data: { id: string } | null; error: { message: string } | null }>;
          };
        };
      })
        .insert(sat.payload)
        .select("id")
        .maybeSingle();
      if (satError || !satRow) {
        toast.error(
          ar
            ? `أُنشئ الملف لكن تعذّر إنشاء صفحة الدليل: ${satError?.message ?? ""}`
            : `Profile created, but the directory page failed: ${satError?.message ?? ""}`,
        );
      } else {
        satelliteId = satRow.id;
      }
    }

    setSaving(false);
    resetForm();
    setOpen(false);
    toast.success(ar ? "تم إنشاء ملف غير مُطالَب به" : "Unclaimed profile created");
    await queryClient.invalidateQueries({ queryKey: ["admin-assisted-providers"] });
    await generateLink(inserted.id, sat && satelliteId ? { table: sat.table, id: satelliteId } : null);
  };

  const generateLink = async (
    providerId: string,
    satellite?: { table: string; id: string } | null,
  ) => {
    const { data, error } = await supabase.rpc("admin_create_provider_claim", {
      _provider_id: providerId,
      ...(satellite ? { _satellite_table: satellite.table, _satellite_id: satellite.id } : {}),
    });
    if (error || !data) {
      toast.error(error?.message || (ar ? "تعذّر إنشاء الرابط" : "Could not create the link"));
      return;
    }
    const url = absoluteUrl(`/claim/${data as string}`);
    setLinks((prev) => ({ ...prev, [providerId]: url }));
    await queryClient.invalidateQueries({ queryKey: ["admin-claim-tokens"] });
    try {
      await navigator.clipboard.writeText(url);
      toast.success(ar ? "تم نسخ الرابط" : "Link copied");
    } catch {
      toast.success(ar ? "تم إنشاء الرابط" : "Link created");
    }
  };


  const copy = async (url: string) => {
    try {
      await navigator.clipboard.writeText(url);
      toast.success(ar ? "تم النسخ" : "Copied");
    } catch {
      toast.error(ar ? "تعذّر النسخ" : "Could not copy");
    }
  };

  return (
    <div className="space-y-3" dir={ar ? "rtl" : "ltr"}>
      <div className="rounded-xl border border-border bg-background p-4">
        <p className="text-sm font-bold text-foreground">
          {ar ? "تسجيل بمساعدة" : "Assisted signup"}
        </p>
        <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
          {ar
            ? "أنشئ ملف مزوّد بالنيابة عنه أثناء الجلوس معه، ثم أعطه رابط الاستحواذ ليربطه بحسابه لاحقًا. الملف لا يستقبل حجوزات ولا رسائل قبل الاستحواذ."
            : "Create a provider profile on someone's behalf while sitting with them, then hand them a claim link to bind it to their account. An unclaimed profile takes no bookings or messages."}
        </p>
        <Button className="mt-3 w-full gap-2" onClick={() => setOpen((v) => !v)}>
          <Plus className="w-4 h-4" />
          {open ? (ar ? "إخفاء النموذج" : "Hide form") : ar ? "إنشاء ملف مزوّد" : "Create a provider profile"}
        </Button>
        <button
          onClick={() => setAdoptOpen((v) => !v)}
          className="mt-2 w-full min-h-[44px] rounded-xl border border-border text-xs font-semibold text-foreground flex items-center justify-center gap-2"
        >
          <Star className="w-3.5 h-3.5" />
          {adoptOpen
            ? ar ? "إخفاء الدليل" : "Hide directory"
            : ar ? "دعوة شخصية من دليل «من يكون من»" : "Invite an existing Who's Who entry"}
        </button>
      </div>

      {adoptOpen && (
        <div className="rounded-xl border border-border bg-background p-4 space-y-3">
          <p className="text-xs text-muted-foreground leading-relaxed">
            {ar
              ? "مدخلات الدليل بدون مالك. اختر شخصًا لإنشاء ملف مزوّد مطابق ورابط استحواذ ترسله له."
              : "Directory entries with no owner. Pick a person to create the matching provider profile and a claim link to send them."}
          </p>
          <input
            value={adoptSearch}
            onChange={(e) => setAdoptSearch(e.target.value)}
            placeholder={ar ? "ابحث بالاسم" : "Search by name"}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          />
          {adoptResults.map((e) => (
            <div key={e.id} className="flex items-center gap-2 border-t border-border pt-2">
              <p className="text-sm text-foreground truncate min-w-0">
                {ar ? e.name_ar || e.name_en : e.name_en}
              </p>
              <button
                onClick={() => adopt(e)}
                disabled={adopting === e.id}
                className="ms-auto shrink-0 min-h-[44px] px-3 rounded-xl border border-border text-xs font-semibold flex items-center gap-2"
              >
                {adopting === e.id ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Link2 className="w-3.5 h-3.5" />}
                {ar ? "رابط استحواذ" : "Claim link"}
              </button>
            </div>
          ))}
          {adoptResults.length === 0 && (
            <p className="text-xs text-muted-foreground">{ar ? "لا نتائج" : "No matches"}</p>
          )}
        </div>
      )}

      {open && (
        <div className="rounded-xl border border-border bg-background p-4 space-y-3">
          <div>
            <label className="text-xs font-semibold text-foreground block mb-1">
              {ar ? "بيقول عن نفسه" : "They describe themselves as"}
            </label>
            <select
              value={intentKey}
              onChange={(e) => setIntentKey(e.target.value)}
              className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
            >
              {ADMIN_ROLE_OPTIONS.map((i) => (
                <option key={i.key} value={i.key}>
                  {i.statement[lang]}
                </option>
              ))}
            </select>
          </div>


          <PhotoPicker files={photo} onChange={setPhoto} max={1} hint={ar ? "صورة" : "Photo"} />

          <input
            value={nameAr}
            onChange={(e) => setNameAr(e.target.value)}
            dir="rtl"
            placeholder={ar ? "الاسم بالعربية" : "Name in Arabic"}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          />
          <input
            value={nameEn}
            onChange={(e) => setNameEn(e.target.value)}
            dir="ltr"
            placeholder={ar ? "الاسم بالإنجليزية (اختياري)" : "Name in English"}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          />
          <textarea
            value={bio}
            onChange={(e) => setBio(e.target.value)}
            rows={3}
            placeholder={ar ? "نبذة" : "Short bio"}
            className="w-full px-3 py-2 rounded-xl border border-border bg-card text-sm resize-none"
          />
          <select
            value={cityId}
            onChange={(e) => setCityId(e.target.value)}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          >
            <option value="">{ar ? "اختر المدينة" : "Select a city"}</option>
            {cities.map((c) => (
              <option key={c.id} value={c.id}>
                {ar ? c.name_ar || c.name_en : c.name_en}
              </option>
            ))}
          </select>
          <input
            value={whatsapp}
            onChange={(e) => setWhatsapp(e.target.value)}
            dir="ltr"
            inputMode="tel"
            placeholder={ar ? "رقم الواتساب" : "WhatsApp number"}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          />
          <input
            value={specialties}
            onChange={(e) => setSpecialties(e.target.value)}
            placeholder={ar ? "تخصصات، بينها فاصلة" : "Specialities, comma separated"}
            className="w-full min-h-[44px] px-3 rounded-xl border border-border bg-card text-sm"
          />

          <Button className="w-full gap-2" onClick={create} disabled={saving}>
            {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <UserPlus className="w-4 h-4" />}
            {ar ? "إنشاء ورابط استحواذ" : "Create and generate claim link"}
          </Button>
        </div>
      )}

      {isLoading && <p className="text-sm text-muted-foreground">{ar ? "جارٍ التحميل…" : "Loading…"}</p>}
      {!isLoading && managed.length === 0 && (
        <p className="text-sm text-muted-foreground">
          {ar ? "لا توجد ملفات مُنشأة بمساعدة بعد." : "No assisted profiles yet."}
        </p>
      )}

      {managed.map((r) => {
        const token = tokenFor(r.id);
        const claimed = !!r.user_id;
        const link = links[r.id];
        return (
          <div key={r.id} className="rounded-xl border border-border bg-background p-4 space-y-2">
            <div className="flex items-start gap-2">
              <div className="min-w-0">
                <p className="text-sm font-bold text-foreground truncate">
                  {ar ? r.name_ar || r.name_en : r.name_en}
                </p>
                <p className="text-xs text-muted-foreground">
                  {ADMIN_ROLE_OPTIONS.find((i) => i.role === r.role)?.statement[lang] || r.role}
                  {r.city_en ? ` · ${r.city_en}` : ""}
                </p>
              </div>
              <span
                className={`ms-auto shrink-0 inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                  claimed ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"
                }`}
              >
                {claimed ? <UserCheck className="w-3 h-3" /> : <Link2 className="w-3 h-3" />}
                {claimed ? (ar ? "تم الاستحواذ" : "Claimed") : ar ? "بانتظار الاستحواذ" : "Unclaimed"}
              </span>
            </div>

            {!claimed && token && (
              <p className="text-[11px] text-muted-foreground">
                {ar ? "الرابط ينتهي في " : "Link expires "}
                {new Date(token.expires_at).toLocaleDateString(ar ? "ar-EG" : "en-US")}
              </p>
            )}

            {link && (
              <div className="flex items-center gap-2">
                <code className="flex-1 min-w-0 truncate text-[11px] bg-muted rounded-lg px-2 py-1.5" dir="ltr">
                  {link}
                </code>
                <button
                  onClick={() => copy(link)}
                  aria-label={ar ? "نسخ" : "Copy"}
                  className="min-w-[44px] min-h-[44px] flex items-center justify-center rounded-lg border border-border"
                >
                  <Copy className="w-4 h-4" />
                </button>
              </div>
            )}

            {!claimed && (
              <button
                onClick={() => generateLink(r.id)}
                className="w-full min-h-[44px] rounded-xl border border-border text-xs font-semibold text-foreground flex items-center justify-center gap-2"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                {token
                  ? ar
                    ? "إنشاء رابط جديد (يلغي القديم)"
                    : "Generate a new link (cancels the old one)"
                  : ar
                    ? "إنشاء رابط استحواذ"
                    : "Generate claim link"}
              </button>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default AdminAssistedProviders;
