// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-experiences.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-experiences.ts
var search_experiences_default = defineTool({
  name: "search_experiences",
  title: "Search experiences",
  description: "Search bookable Egypt experiences by keyword, theme, or maximum price. Returns title, region, theme, price in EGP and rating.",
  inputSchema: {
    query: z.string().trim().optional().describe("Keyword matched against the English title."),
    theme: z.string().trim().optional().describe("Theme filter, e.g. culture, nature, food."),
    max_price: z.number().positive().optional().describe("Maximum price in EGP."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, theme, max_price, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("experiences").select("id, slug, title_en, title_ar, theme, price, rating, region_id, city_id, duration_minutes").limit(limit ?? 10);
    if (query) q = q.ilike("title_en", `%${query}%`);
    if (theme) q = q.eq("theme", theme);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { experiences: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-events.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_events_default = defineTool2({
  name: "list_upcoming_events",
  title: "List upcoming events",
  description: "List published upcoming events, optionally filtered by keyword, category, or free-only, ordered by start date.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Keyword matched against the English event title."),
    category: z2.string().trim().optional().describe("Event category filter."),
    free_only: z2.boolean().optional().describe("Only return free events."),
    limit: z2.number().int().min(1).max(50).default(10).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, free_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = supabaseForUser(ctx).from("events").select("id, slug, title_en, title_ar, start_date, event_time, venue_en, location_en, category, price, is_free, capacity").eq("status", "published").gte("start_date", today).order("start_date", { ascending: true }).limit(limit ?? 10);
    if (query) q = q.ilike("title_en", `%${query}%`);
    if (category) q = q.eq("category", category);
    if (free_only) q = q.eq("is_free", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trips.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_trips_default = defineTool3({
  name: "list_trips",
  title: "List trips",
  description: "List multi-day Egypt trips with route, duration in days, price in EGP and rating.",
  inputSchema: {
    query: z3.string().trim().optional().describe("Keyword matched against the English trip title."),
    theme: z3.string().trim().optional().describe("Trip theme filter."),
    max_days: z3.number().int().positive().optional().describe("Maximum trip duration in days."),
    limit: z3.number().int().min(1).max(50).default(10).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, theme, max_days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("trips").select("id, slug, title_en, title_ar, route_en, duration_days, price, rating, theme, trip_type").limit(limit ?? 10);
    if (query) q = q.ilike("title_en", `%${query}%`);
    if (theme) q = q.eq("theme", theme);
    if (typeof max_days === "number") q = q.lte("duration_days", max_days);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-bookings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var my_bookings_default = defineTool4({
  name: "my_bookings",
  title: "My bookings",
  description: "List the signed-in user's experience bookings with status, guests and amounts in EGP.",
  inputSchema: {
    status: z4.string().trim().optional().describe("Filter by booking status, e.g. paid or pending."),
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("bookings").select("id, experience_id, guests, status, total_amount_egp, paid_at, created_at").eq("visitor_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-event-tickets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var my_event_tickets_default = defineTool5({
  name: "my_event_tickets",
  title: "My event tickets",
  description: "List the signed-in user's event ticket orders with reference code, quantity and total in EGP.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("event_tickets").select("id, reference, event_id, attendee_name, quantity, total_egp, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-saved-itineraries.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_saved_itineraries_default = defineTool6({
  name: "list_saved_itineraries",
  title: "List saved itineraries",
  description: "List the signed-in user's saved trip itineraries (title, destination, duration).",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).default(20).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("saved_itineraries").select("id, title, destination, duration_days, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { itineraries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-itinerary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var save_itinerary_default = defineTool7({
  name: "save_itinerary",
  title: "Save itinerary",
  description: "Save a trip itinerary to the signed-in user's account so it appears in the app's Trip Planner.",
  inputSchema: {
    title: z7.string().trim().min(1).max(120).describe("Short itinerary title."),
    plan: z7.string().trim().min(1).describe("The itinerary content, Markdown allowed."),
    destination: z7.string().trim().optional().describe("Main destination, e.g. Luxor."),
    duration_days: z7.number().int().min(1).max(60).optional().describe("Trip length in days.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, plan, destination, duration_days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("saved_itineraries").insert({
      user_id: ctx.getUserId(),
      title,
      destination: destination ?? null,
      duration_days: duration_days ?? null,
      messages: [{ role: "assistant", content: plan }]
    }).select("id, title").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved itinerary "${data.title}" (id ${data.id}).` }],
      structuredContent: { itinerary: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "meacccbwpzrrcoanlojw";
var mcp_default = defineMcp({
  name: "remix-of-sandal-journeys",
  title: "Remix of Sandal Journeys",
  version: "0.1.0",
  instructions: "Tools for Sandal, a slow-travel Egypt platform. Browse experiences, upcoming events and multi-day trips, read the signed-in user's bookings, event tickets and saved itineraries, and save new itineraries to their account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_experiences_default,
    list_upcoming_events_default,
    list_trips_default,
    my_bookings_default,
    my_event_tickets_default,
    list_saved_itineraries_default,
    save_itinerary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
